## Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [ ]:
lis = [1, 2, 3]
print("Python list multiplication", lis * 2)

lis = [1, 2, 3]
print("Python list addition ", lis + [4, 5, 6])

arr = np.array([1, 2, 3])
print("Python array multiplication ", arr * 2)             #element wise multiplication

arr = np.array([1, 2, 3])
print("Python array addition ", arr + [4, 5, 6])             #element wise addition


Python list multiplication [1, 2, 3, 1, 2, 3]
Python list addition  [1, 2, 3, 4, 5, 6]
Python array multiplication  [2 4 6]
Python array addition  [5 7 9]


In [15]:
import time
start = time.time()

lis = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
arr = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)



 List operation time:  0.06951212882995605

 Numpy operation time:  0.0023093223571777344


### creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("\nzeros array: \n", zeros)

ones = np.ones((2, 3))
print("\none array: \n", ones)

full = np.full((2, 2), 7)       # creates a 2x2 array filled with the value 7
print("\nfull array: \n", full)

random = np.random.random((2, 3))
print("\nrandom array: \n", random)

sequence = np.arange(0, 11, 2)    # creates an array with values from 0 to 10 (exclusive) with a step of 2
print("\nsequence array: \n", sequence)



zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

full array: 
 [[7 7]
 [7 7]]

random array: 
 [[0.99509181 0.74179764 0.51598787]
 [0.89881197 0.27875509 0.91379502]]

sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [10]:
arr = np.array([[1, 2, 3], 
                [4, 5.6, "abc"]])

print("Shape ", arr.shape)   # returns a tuple representing the dimensions of the array
print("Shape of tensor ", tensor.shape)

print("Dimension ", arr.ndim)  # returns the number of dimensions (axes) of the array
print("Dimension of tensor ", tensor.ndim)

print("Size ", arr.size)  # returns the total number of elements in the array
print("DType ", arr.dtype) # returns the data type of the elements in the array

Shape  (2, 3)
Shape of tensor  (2, 2, 2)
Dimension  2
Dimension of tensor  3
Size  6
DType  <U32


### Array Reshaping

In [13]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
