## Numpy Array operations

In [1]:
import numpy as np

In [2]:
print("hello")

hello


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3]) 

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
                   
print("Specific element", arr_2d[1, 2])
print("Specific element", arr_2d[1][2])   # Both are same

print("Slicing 2D array", arr_2d[:, 2])
print("Slicing 2D array", arr_2d[0:2, 0:2])
print("Slicing 2D array with step", arr_2d[0:3:2, 0:3:2])
print("Slicing 2D array with step", arr_2d[0:3:2, :])


Specific element 6
Specific element 6
Slicing 2D array [3 6 9]
Slicing 2D array [[1 2]
 [4 5]]
Slicing 2D array with step [[1 3]
 [7 9]]
Slicing 2D array with step [[1 2 3]
 [7 8 9]]


## Sorting

In [5]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter


In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [7]:
# Using boolean indexing to filter numbers greater than 5

mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [8]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibilty

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])
d = np.array([[1], [2], [3]])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape)
print("Compatibility shapes", d.T.shape)
print("Compatibility shapes", a.T.shape)
print("Compatibility shapes", d.shape)

# don't understand why a and transposed d are not compatible for concatenation
# print("Compatibility shapes", a.shape == d.T.shape)
# print("Compatibility shapes", np.concatenate((a, d.T)))
# The above line will throw an error because the shapes of a and d.T are not compatible for concatenation.
# I am asking, why?

# Then tell me how to make them compatible for concatenation.
# To make them compatible for concatenation, we can reshape a to have the same number of dimensions as d.T.
print(a)
a_reshaped = a.reshape(1, -1)  # Reshape a to have 1 row and as many columns as needed
print(a_reshaped)
# print("Compatibility shapes", a_reshaped.shape == d.T.shape)
# print("Compatibility shapes", np.concatenate((a_reshaped, d.T)))


Compatibility shapes False
Compatibility shapes (3,)
Compatibility shapes (1, 3)
Compatibility shapes (3,)
Compatibility shapes (3, 1)
[1 2 3]
[[1 2 3]]


In [25]:
# A 1D array can only be concatenated with another 1D array.
# For a 2D array, its transpose is usually NOT compatible with a 1D array.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])      # 1D array, so arr2.T is still 1D

print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)
print("arr2.T shape:", arr2.T.shape)
print("Compatible:", arr1.shape == arr2.T.shape)
print("Concatenated:", np.concatenate((arr1, arr2.T)))

# Example of NOT compatible with a 1D array
arr3 = np.array([[4], [5], [6]])  # 2D array
print("arr3.T shape:", arr3.T.shape)
print("Compatible with arr1:", arr1.shape == arr3.T.shape)

arr1 shape: (3,)
arr2 shape: (3,)
arr2.T shape: (3,)
Compatible: True
Concatenated: [1 2 3 4 5 6]
arr3.T shape: (1, 3)
Compatible with arr1: False


In [30]:
# Example of a 2D array
two_d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("two_d shape:", two_d.shape)
print(two_d)

# Example of an array whose transpose is compatible with the 2D array
# arr3 has shape (3, 1), so arr3.T has shape (1, 3)
arr3 = np.array([[10],
                 [11],
                 [12]])
print("arr3 shape:", arr3.shape)
print("arr3.T shape:", arr3.T.shape)

# These can be concatenated along axis 0 because both have 3 columns
compatible = np.concatenate((two_d, arr3.T), axis=0)
print("Concatenated result:")
print(compatible)

two_d shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3 shape: (3, 1)
arr3.T shape: (1, 3)
Concatenated result:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
original = np.array([[1, 2], 
                     [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after the deletion: ", deleted)

Array after the deletion:  [1 2 4 5]
